version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.18.0

    working_directory: ~/app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Run Tests
      - run:
          name: Run Tests
          command: npm test

  deploy:
    docker:
      - image: cimg/aws:2023.12
    steps:
      - checkout

      # Install Deployment Dependencies
      - run:
          name: Install Deployment Dependencies
          command: python3 -m pip install --upgrade --user awsebcli

      - run:
          name: Deploy to ElasticBeanstalk
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION
            eb init <app-name> --region $AWS_REGION --platform "Docker running on 64bit Amazon Linux 2023"
            eb use <environment name>
            eb deploy

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
