#cloud-config

# Azure VM Cloud-Init Configuration
# Equivalent to the AWS user-data.sh script for EC2 instances

package_update: true
package_upgrade: true

packages:
    - nginx

# Run commands after packages are installed
runcmd:
    # Start and enable nginx service
    - systemctl start nginx
    - systemctl enable nginx

    # Capture the launch time
    - echo "$(date)" > /var/www/html/launch-time.txt

    # Create the main index.html page
    - |
        LAUNCH_TIME=$(cat /var/www/html/launch-time.txt)
        cat > /var/www/html/index.html << EOF
        <!DOCTYPE html>
        <html>
        <head>
            <title>Hello World - Azure Migration Lab</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    text-align: center;
                    background-color: #f0f0f0;
                    padding: 50px;
                }
                .container {
                    background-color: white;
                    padding: 30px;
                    border-radius: 10px;
                    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                    max-width: 600px;
                    margin: 0 auto;
                }
                h1 {
                    color: #333;
                    margin-bottom: 20px;
                }
                .info {
                    color: #666;
                    margin-top: 20px;
                }
                .azure-logo {
                    color: #0078d4;
                    font-weight: bold;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1> Hello World from Azure VM!</h1>
                <p>This is a simple web server running on Microsoft Azure Virtual Machine.</p>
                <p class="azure-logo">Azure Migration Lab</p>
                <div class="info">
                    <p>Server: Ubuntu</p>
                    <p>Web Server: Nginx</p>
                    <p>Instance launched: ${LAUNCH_TIME}</p>
                </div>
            </div>
        </body>
        </html>
        EOF

    # Set proper permissions for the index file
    - chmod 644 /var/www/html/index.html

    # Create a status page with Azure metadata (server-side generated)
    - |
        # Get metadata using Azure Instance Metadata Service during cloud-init
        VM_NAME=$(curl -H "Metadata:true" "http://169.254.169.254/metadata/instance/compute/name?api-version=2021-02-01&format=text")
        RESOURCE_GROUP=$(curl -H "Metadata:true" "http://169.254.169.254/metadata/instance/compute/resourceGroupName?api-version=2021-02-01&format=text")
        LOCATION=$(curl -H "Metadata:true" "http://169.254.169.254/metadata/instance/compute/location?api-version=2021-02-01&format=text")
        VM_SIZE=$(curl -H "Metadata:true" "http://169.254.169.254/metadata/instance/compute/vmSize?api-version=2021-02-01&format=text")
        SUBSCRIPTION_ID=$(curl -H "Metadata:true" "http://169.254.169.254/metadata/instance/compute/subscriptionId?api-version=2021-02-01&format=text")

        cat > /var/www/html/status.html << EOF
        <!DOCTYPE html>
        <html>
        <head>
            <title>Azure VM Status</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    margin: 40px;
                    background-color: #f5f5f5;
                }
                .container {
                    background-color: white;
                    padding: 20px;
                    border-radius: 8px;
                    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                }
                .azure-blue {
                    color: #0078d4;
                }
                .status-ok {
                    color: #28a745;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1 class="azure-blue">Azure VM Status</h1>
                <p class="status-ok"> Nginx is running successfully!</p>
                <p><strong>VM Name:</strong> ${VM_NAME}</p>
                <p><strong>Resource Group:</strong> ${RESOURCE_GROUP}</p>
                <p><strong>Location:</strong> ${LOCATION}</p>
                <p><strong>VM Size:</strong> ${VM_SIZE}</p>
                <p><strong>Subscription ID:</strong> ${SUBSCRIPTION_ID}</p>
                <p><strong>Metadata Service:</strong> Azure Instance Metadata Service</p>
                <p><strong>Status Generated:</strong> $(date)</p>
                
                <hr>
                <h3>Migration Lab Notes</h3>
                <p>This page was generated server-side during VM launch using Azure Instance Metadata Service.</p>
                <p>The metadata is embedded in the HTML and will be preserved with the VM image.</p>
            </div>
        </body>
        </html>
        EOF

    # Set permissions for status page
    - chmod 644 /var/www/html/status.html

    # Restart nginx to ensure everything is loaded
    - systemctl restart nginx

    # Log the completion
    - echo "Cloud-init configuration completed successfully at $(date)" >> /var/log/cloud-init-custom.log

# Write additional files
write_files:
    - path: /etc/nginx/sites-available/migration-lab
      content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              
              root /var/www/html;
              index index.html index.htm index.nginx-debian.html;
              
              server_name _;
              
              location / {
                  try_files $uri $uri/ =404;
              }
              
              # Add a custom header to identify this as a migrated server
              add_header X-Migration-Lab "Azure-VM" always;
          }
      permissions: "0644"

# Final message
final_message: |
    Cloud-init configuration complete!

    The web server should now be available at:
    - Main page: http://[VM_PUBLIC_IP]/
    - Status page: http://[VM_PUBLIC_IP]/status.html

    Migration lab setup complete on Azure VM.
