---
- name: restart ssh
  ansible.builtin.service:
    name: "{{ security_sshd_name }}"
    state: "{{ security_ssh_restart_handler_state }}"

- name: reload fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: reloaded

- name: reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
