---
security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_restart_handler_state: restarted

security_autoupdate_enabled: true
security_autoupdate_blacklist: []
security_autoupdate_additional_origins: []

security_autoupdate_reboot: "false"
security_autoupdate_reboot_time: "03:00"
security_autoupdate_mail_to: ""
security_autoupdate_mail_on_error: true

security_fail2ban_enabled: true
security_fail2ban_custom_configuration_template: "jail.local.j2"

security_backend_service_name: "backend_service"
security_app_environment: production
